# Generated by Django 2.0.1 on 2018-01-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_auto_20180111_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_login',
            field=models.CharField(default='', max_length=12, verbose_name='最后登录'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='', max_length=100, verbose_name='密码'),
        ),
    ]
