# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-13 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0012_auto_20180113_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=django.utils.timezone.now, max_length=20, verbose_name='发送时间'),
        ),
    ]
