# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-13 20:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0014_auto_20180113_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime.now, max_length=20, verbose_name='发送时间'),
        ),
    ]
